// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import robot.Constants.DriveTrainConstants;

import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveDriveOdometry;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class drivetrainSubSys extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    private final SwerveModule frontLeft = new SwerveModule(
        DriveTrainConstants.kFrontLeftDriveMotorPort,
        DriveTrainConstants.kFrontLeftTurningMotorPort,
        DriveTrainConstants.kFrontLeftDriveEncoderReversed,
        DriveTrainConstants.kFrontLeftTurningEncoderReversed,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderPort,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kFrontLeftDriveAbsoluteEncoderReversed);

    private final SwerveModule frontRight = new SwerveModule(
        DriveTrainConstants.kFrontRightDriveMotorPort,
        DriveTrainConstants.kFrontRightTurningMotorPort,
        DriveTrainConstants.kFrontRightDriveEncoderReversed,
        DriveTrainConstants.kFrontRightTurningEncoderReversed,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderPort,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kFrontRightDriveAbsoluteEncoderReversed);

    private final SwerveModule backLeft = new SwerveModule(
        DriveTrainConstants.kBackLeftDriveMotorPort,
        DriveTrainConstants.kBackLeftTurningMotorPort,
        DriveTrainConstants.kBackLeftDriveEncoderReversed,
        DriveTrainConstants.kBackLeftTurningEncoderReversed,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderPort,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kBackLeftDriveAbsoluteEncoderReversed);

    private final SwerveModule backRight = new SwerveModule(
        DriveTrainConstants.kBackRightDriveMotorPort,
        DriveTrainConstants.kBackRightTurningMotorPort,
        DriveTrainConstants.kBackRightDriveEncoderReversed,
        DriveTrainConstants.kBackRightTurningEncoderReversed,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderPort,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderOffsetRad,
        DriveTrainConstants.kBackRightDriveAbsoluteEncoderReversed);

    // Gyro
    private final AHRS gyro = new AHRS(SPI.Port.kMXP);

    // Odometry
    private final SwerveDriveOdometry odometer = new SwerveDriveOdometry( 
        DriveTrainConstants.kDriveKinematics,
        new Rotation2d(0));

    public drivetrainSubSys() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        new Thread(() -> {
            try {
                Thread.sleep(1000);
                zeroHeading();
            } catch (Exception e) {
            }
        }).start();
    }

    @Override
    public void periodic() {
        odometer.update(getGyroHeadingRotation2d(), frontLeft.getState(), frontRight.getState(), backLeft.getState(),
                backRight.getState());
        updateShuffleboard();

        SmartDashboard.putNumber("Robot Heading Degrees", getHeadingDegrees());
        SmartDashboard.putString("Robot Loc Meters", getPoseMeters().getTranslation().toString());
        SmartDashboard.putNumber("Robot Loc X Ft", Units.metersToFeet(getPoseMeters().getX()));
        SmartDashboard.putNumber("Robot Loc Y Ft", Units.metersToFeet(getPoseMeters().getY()));
        SmartDashboard.putString("Robot Kinematics", DriveTrainConstants.kDriveKinematics.toString());
        frontLeft.updateShuffleBoard();
        frontRight.updateShuffleBoard();
        backLeft.updateShuffleBoard();
        backRight.updateShuffleBoard();
    }
    
    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void zeroHeading() {
        gyro.reset();
    }

    public double getHeadingDegrees() {
        // This will return values from -180CW to +180CCW degrees of yaw
        return -Math.IEEEremainder(gyro.getAngle(), 360);
    }

    public Rotation2d getGyroHeadingRotation2d() {
        // this will return a Rotation2d object of the yaw value -180 to +180 degree
        return Rotation2d.fromDegrees(getHeadingDegrees());
    }

    public Pose2d getPoseMeters() {
        return odometer.getPoseMeters();
    }

    
    public Pose2d getPoseFeet() {
        return odometer.getPoseMeters();
    }

    public void resetOdometry(Pose2d pose) {
        odometer.resetPosition(pose, getGyroHeadingRotation2d());
    }

    public void stopModules() {
        // Should this be done through setModuleStates method ?????
        frontLeft.stop();
        frontRight.stop();
        backLeft.stop();
        backRight.stop();
    }

    public void setSingleModuleState(int canID, double speed, double angle) { 
        // This is a manual drive of the wheels used only to test and get calibration data  
        // speed in Meters/sec , angle in Radians +PI Full CCW -PI Full CW     
        if (canID == DriveTrainConstants.kFrontLeftDriveMotorPort){
            frontLeft.setSingleModule( speed, angle);
        } else if (canID == DriveTrainConstants.kFrontRightDriveMotorPort){ 
            frontRight.setSingleModule( speed, angle);
        } else if (canID == DriveTrainConstants.kBackLeftDriveMotorPort){ 
            backLeft.setSingleModule( speed, angle);
        } else if (canID == DriveTrainConstants.kBackRightDriveMotorPort){ 
            backRight.setSingleModule( speed, angle);}
    }


    public void drive(Translation2d translation, double rotation, boolean fieldRelative, boolean isOpenLoop) { 
        // if (Math.abs(rotation)< 0.03) {
        //     rotation = 0.0;
        // }

    
        // Step 1 - Create a "Chassis Speeds" Object from field velocity targets and current Gyro Angle
        ChassisSpeeds speeds;
        if( fieldRelative ){
            // Field Relative
            speeds = ChassisSpeeds.fromFieldRelativeSpeeds(
                translation.getX(),
                translation.getY(),
                rotation,
                getGyroHeadingRotation2d());
        } else {
            // Chassis Relative
            speeds = new ChassisSpeeds(
                translation.getX(),
                translation.getY(),
                rotation);
        }

        // Step 4 - Create a "Swerve Module States" Array object from the "chassis Speeds" object
        // This creates a SwerveModuleState Array of Swerve Drive States.
        // Each array element contains "Drive-Velocity" and "Turn-Angle" values. 
        SwerveModuleState[] swerveModuleStates = 
                DriveTrainConstants.kDriveKinematics.toSwerveModuleStates(speeds);

        // This is the normal method used to drive the wheels!
        // Make sure all wheels are at the same Velocity (in the "desiredStates" Array)
        SwerveDriveKinematics.desaturateWheelSpeeds(
            swerveModuleStates, 
            DriveTrainConstants.kPhysicalMaxSpeedMetersPerSecond);

        // Step 5 - Send "Swerve Module States" Array to Drivetrain Motors
        // Send State (Velocity and Angle) to Each Swerve Drive Motor
        frontLeft.setDesiredState(swerveModuleStates[0], isOpenLoop);
        frontRight.setDesiredState(swerveModuleStates[1], isOpenLoop);
        backLeft.setDesiredState(swerveModuleStates[2], isOpenLoop);
        backRight.setDesiredState(swerveModuleStates[3], isOpenLoop);
    }

    // ---------------------- Drive the Swerve Module Motors --------------------------
    public void setSwerveModulesStates(SwerveModuleState[] desiredStates) {
        // Make sure all wheels are at the same Velocity (in the "desiredStates" Array)
        SwerveDriveKinematics.desaturateWheelSpeeds(
                desiredStates, 
                DriveTrainConstants.kPhysicalMaxSpeedMetersPerSecond);
        // Send State (Velocity and Angle) to Each Swerve Drive Motor
        frontLeft.setDesiredState(desiredStates[0], false);
        frontRight.setDesiredState(desiredStates[1], false);
        backLeft.setDesiredState(desiredStates[2], false);
        backRight.setDesiredState(desiredStates[3], false);
    }
    public void updateShuffleboard(){
        // SmartDashboard.putNumber("Robot Heading Degrees", getHeadingDegrees());
        // SmartDashboard.putString("Robot Loc Meters", getPoseMeters().getTranslation().toString());
        // SmartDashboard.putNumber("Robot Loc X Ft", Units.metersToFeet(getPoseMeters().getX()));
        // SmartDashboard.putNumber("Robot Loc Y Ft", Units.metersToFeet(getPoseMeters().getY()));
        // SmartDashboard.putString("Robot Kinematics", DriveTrainConstants.kDriveKinematics.toString());
        frontLeft.updateShuffleBoard();
        frontRight.updateShuffleBoard();
        backLeft.updateShuffleBoard();
        backRight.updateShuffleBoard();
    }
}


